### ISSUE TITLE
How can I use this extension?

### ISSUE THREAD

**Issue by marouenbg** [team-monolith-product/jupyterlab-google-analytics#11]
Hey @a3626a ,

I want to track the usage on a JupyterHub server using Google Analytics, how can I use your package for this?

Marouen

**Comment by a3626a** [comment]
I will add some documentation at README and let you know. Will be done in 24h.

[My sentry extension](https://github.com/team-monolith-product/jupyterlab-sentry#sentry-dsn) uses same approach (setting). 

You need to put GA tracking id in settings rather than Sentry DSN.

Check this [schema file](https://github.com/team-monolith-product/jupyterlab-google-analytics/blob/main/schema/plugin.json) for setting details. Or you can open Jupyter Lab Setting Editor UI to check the settings schema after install this extension.

**Comment by a3626a** [comment]
If you have any problem, please re-open  this issue, or create another issue for detailed problem.
